my_car_site/cars/urls.py
from django.urls import path
from . import views


app_name = 'cars'

#domain.com/cars/list
urlpatterns = [
    path('list/', views.list, name='list'),
    path('delete/', views.delete, name='delete'),
    path('add/', views.add, name='add'),
]

my_car_site/my_car_site/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('cars.urls')),
]

my_car_site/cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    brand = models.CharField(max_length=100)
    year = models.IntegerField()

    def __str__(self):
        return f"Car is {self.brand} {self.year}"

my_car_site/cars/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def list(request):
    all_cars = models.Car.objects.all()
    context = {
        'all_cars': all_cars
    }
    return render(request, 'cars/list.html', context = context)

@csrf_exempt
def delete(request):
    if request.POST:
        car_id = request.POST['pk']
        try:
            car = models.Car.objects.get(id=car_id)
            car.delete()
            return redirect(reverse('cars:list'))
        except:
            print("Car not found")
            return redirect(reverse('cars:list'))
    else:
        return render(request, 'cars/delete.html')

# This decorator is used to allow POST request without csrf token
@csrf_exempt
def add(request):
    if request.POST:
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand=brand, year=year)
        # If user submit a new car, redirect to the list page
        return redirect(reverse('cars:list'))
    else:
        return render(request, 'cars/add.html')
    

my_car_site/cars/templates/cars/add.html
{% extends "base.html" %}

{% block content %}
<div class = 'container'>
    <h1>add html</h1>
    <h2>Add a new car to the database</h2>
    <form action="" method="POST">
        <div class = "form-group">
            <label for="brand">Brand</label>
            <input class="form-control" type="text" id="brand", name="brand">
        </div>
        <div class = "form-group">
            <label for="year">Year:</label>
            <input class = "form-control" type="text", id = "year", name = "year">
        </div>
        <input class = 'btn btn-primary' type="submit" name="" id="">
    </form>
</div>

{% endblock %}

my_car_site/cars/templates/cars/delete.html
{% extends "base.html" %}

{% block content %}
<div class = "container">
    <h1>delete html</h1>
    <h2>Delete a car from the database using primary key</h2>
    <form action="" method="POST">
    <div class="form-group">
        <label for="pk">PK Number: </label>
        <input class = "form-control" type="text" name="pk" id="pk">
    </div>
    <input class = "btn btn-primary" type="submit" value="Delete">
    </form>
</div>

{% endblock %}

my_car_site/cars/templates/cars/list.html
{% extends "base.html" %}

{% block content %}
<div class = 'container'>
    <h1>list html</h1>
    <ul>
        {% for car in all_cars %}
            <li>{{ car }}</li>
        {% endfor %}

</div>

{% endblock %}

my_car_site/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cars:list' %}">LIST</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cars:add' %}">ADD</a>
                </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cars:delete' %}">DELETE</a>
                </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block content %}
    {% endblock %}
</body>
</html>